#!php -f
<?php

error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', 'stdout');

function usage()
{
	print <<<USAGE
 $ admin/migrate ModelName [ModelName2 [ModelName3..]]

 Calling this script with a Model name will cause it to migrate the model to the database

USAGE;
}

if ( count($argv) < 2 ) {
	usage();
	exit (1);
}
array_shift ($argv);

require_once realpath(__DIR__ . '/../configs/bacon.php');

# Start execution timer.
$baconStart = microtime();
$baconStart = explode(' ', $baconStart);
$baconStart = $baconStart[0] + $baconStart[1];

# Root/Front directory.
Config\Bacon::getBaconRoot();

/**
 * This will take care of all including.
 * So basically, this is the only include/require you will ever see in this code (well, almost).
 */
require BACON_ROOT . 'include.php';
\Bacon\Log::init();

foreach ($argv as $name) {

	$model = "Model\\$name";
	\Bacon\Log::debug ("Trying to migrate $model");
	if(!$model::createTable()) {
		\Bacon\Log::debug("Failed to migrate $model");
	}
}
?>
